---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost {{ ansible_hostname }}"
    regexp: ^127\.0\.0\.1

- name: Install essential packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - git
    - python-dev
    - python-netaddr
    - python-pip
    - python-setuptools

- name: Install AWS CLI
  become: yes
  pip:
    name: "{{ item }}"
  when: "{{ gocd_agent.aws.install_cli }}"
  with_items:
    - awscli
    - boto

- name: Add GoCD Apt key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ gocd_agent.repo.key_id }}"
    state: present

- name: Install GoCD repo
  become: yes
  apt_repository:
    repo: "{{ gocd_agent.repo.source }}"
    state: present
    update_cache: yes

- name: Install go-agent
  become: yes
  apt:
    name: "go-agent={{ gocd_agent.version }}"
    state: present
    force: yes

- name: Ensure that the default agent is stopped and disabled
  become: yes
  service:
    enabled: no
    name: go-agent
    state: stopped

- name: Copy go-agent startup script for additional agents
  become: yes
  command: "cp /etc/init.d/go-agent /etc/init.d/go-agent-{{ item }}"
  args:
    creates: "/etc/init.d/go-agent-{{ item }}"
    warn: no
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Ensure startup scripts for additional agents have their own provider name
  become: yes
  lineinfile:
    backrefs: yes
    dest: "/etc/init.d/go-agent-{{ item }}"
    line: "# Provides: go-agent-{{ item }}"
    regexp: "^# Provides: go-agent$"
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Ensure perms on startup scripts for additional agents
  become: yes
  file:
    mode: 754
    path: "/etc/init.d/go-agent-{{ item }}"
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Ensure startup scripts for additional agents are enabled
  become: yes
  service:
    enabled: yes
    name: "go-agent-{{ item }}"
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Create soft links to /usr for additional agents
  become: yes
  file:
    state: link
    src: /usr/share/go-agent
    dest: /usr/share/go-agent-{{ item }}
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Create working directories for additional agents
  become: yes
  file:
    state: directory
    path: "{{ gocd_agent.user_dir }}/work/go-agent-{{ item }}"
    owner: "{{ gocd_agent.user }}"
    group: "{{ gocd_agent.user }}"
  with_sequence: count="{{ gocd_agent.no_of_agents }}"

- name: Create log directories for additional agents
  become: yes
  file:
    state: directory
    path: /var/log/go-agent-{{ item }}
    owner: "{{ gocd_agent.user }}"
    group: "{{ gocd_agent.user }}"
  with_sequence: count="{{ gocd_agent.no_of_agents }}"
